### ISSUE TITLE
Jupyter notebook examples with discretized domain

### ISSUE THREAD

**Issue by zolabar** [mscroggs/symfem#250]
Very interesting project. All those different elements, computed in symbolical from!

It would be great, if there were some jupyter notebook examples, with some 1D and 2D examples, which visualize how the domains get meshed, a line (equidistant vs. non-equidistant), a square (discretized with squares, rectangles or triangles), etc...

With the corresponding solutions, visualized with interpolation, etc...

Thanks!

**Comment by mscroggs** [comment]
This isn't really in the scope of this repo, but something like this would be great as a page on [DefElement](https://defelement.com). You could start a thread in the [discussions](https://github.com/mscroggs/defelement.com/discussions) on the DefElement repo and we can start planning what this might look like
